"""Add production readiness and auditing columns

Revision ID: 91442eb921b4
Revises: 0001_initial
Create Date: 2026-06-27 22:29:23.101789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91442eb921b4'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('alert_rules', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('alert_rules', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('alert_rules', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('alert_rules', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_alert_rules_uuid'), 'alert_rules', ['uuid'], unique=True)
    op.add_column('portfolio_holdings', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('portfolio_holdings', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_portfolio_holdings_uuid'), 'portfolio_holdings', ['uuid'], unique=True)
    op.add_column('portfolios', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('portfolios', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('portfolios', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_portfolios_uuid'), 'portfolios', ['uuid'], unique=True)
    op.add_column('users', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.add_column('watchlists', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('watchlists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('watchlists', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('watchlists', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('watchlists', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_watchlists_uuid'), 'watchlists', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_uuid'), table_name='watchlists')
    op.drop_column('watchlists', 'updated_by')
    op.drop_column('watchlists', 'created_by')
    op.drop_column('watchlists', 'deleted_at')
    op.drop_column('watchlists', 'updated_at')
    op.drop_column('watchlists', 'uuid')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_portfolios_uuid'), table_name='portfolios')
    op.drop_column('portfolios', 'updated_by')
    op.drop_column('portfolios', 'created_by')
    op.drop_column('portfolios', 'deleted_at')
    op.drop_column('portfolios', 'updated_at')
    op.drop_column('portfolios', 'uuid')
    op.drop_index(op.f('ix_portfolio_holdings_uuid'), table_name='portfolio_holdings')
    op.drop_column('portfolio_holdings', 'updated_by')
    op.drop_column('portfolio_holdings', 'created_by')
    op.drop_column('portfolio_holdings', 'deleted_at')
    op.drop_column('portfolio_holdings', 'created_at')
    op.drop_column('portfolio_holdings', 'uuid')
    op.drop_index(op.f('ix_alert_rules_uuid'), table_name='alert_rules')
    op.drop_column('alert_rules', 'updated_by')
    op.drop_column('alert_rules', 'created_by')
    op.drop_column('alert_rules', 'deleted_at')
    op.drop_column('alert_rules', 'updated_at')
    op.drop_column('alert_rules', 'uuid')
    # ### end Alembic commands ###
